#ifndef CONFIG_ANALOG_TORQUE_SENSOR_H
#define CONFIG_ANALOG_TORQUE_SENSOR_H

#define TORQUE_SENSOR_PIN A0
#define TORQUE_SENSOR_OFFSET 0f
#define TORQUE_SENSOR_BUFFER_SIZE 128

#endif // CONFIG_ANALOG_TORQUE_SENSOR_H