.TH "include/forecast/controllers Directory Reference" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/forecast/controllers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBForcePID\&.hpp\fP"
.br
.ti -1c
.RI "file \fBImpedanceControl\&.hpp\fP"
.br
.ti -1c
.RI "file \fBIntegralSlidingMode\&.hpp\fP"
.br
.ti -1c
.RI "file \fBMegaPD\&.hpp\fP"
.br
.in -1c
