.TH "src/controllers Directory Reference" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/controllers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBForcePID\&.cpp\fP"
.br
.ti -1c
.RI "file \fBImpedanceControl\&.cpp\fP"
.br
.ti -1c
.RI "file \fBIntegralSlidingMode\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMegaPD\&.cpp\fP"
.br
.in -1c
