.TH "include/forecast Directory Reference" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/forecast Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBconfig\fP"
.br
.ti -1c
.RI "directory \fBcontrollers\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApp\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcom\&.hpp\fP"
.br
.ti -1c
.RI "file \fBController\&.hpp\fP"
.br
.ti -1c
.RI "file \fBHardware\&.hpp\fP"
.br
.ti -1c
.RI "file \fBStatus\&.hpp\fP"
.br
.in -1c
