.TH "include/USART Directory Reference" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/USART Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClock\&.h\fP"
.br
.ti -1c
.RI "file \fBUSART_interface\&.hpp\fP"
.br
.in -1c
