.TH "config_templates/analog_torque_sensor.h" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_templates/analog_torque_sensor.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTORQUE_SENSOR_PIN\fP   $torque_sensor[pin]$"
.br
.ti -1c
.RI "#define \fBTORQUE_SENSOR_OFFSET\fP   $torque_sensor[offset]$f"
.br
.ti -1c
.RI "#define \fBBUFFER_SIZE\fP   $torque_sensor[buffer_size]$"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFER_SIZE   $torque_sensor[buffer_size]$"

.PP
Definition at line 6 of file analog_torque_sensor\&.h\&.
.SS "#define TORQUE_SENSOR_OFFSET   $torque_sensor[offset]$f"

.PP
Definition at line 5 of file analog_torque_sensor\&.h\&.
.SS "#define TORQUE_SENSOR_PIN   $torque_sensor[pin]$"

.PP
Definition at line 4 of file analog_torque_sensor\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Forecast Nucleo Framework from the source code\&.
