.TH "src/App.cpp" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/App.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <forecast/config/timer\&.h>\fP
.br
\fC#include <debug\&.hpp>\fP
.br
\fC#include <forecast/App\&.hpp>\fP
.br
\fC#include <forecast/com\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBticker\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile bool \fBticker::flag\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBticker::dt_us\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBticker::mTimUserHandle\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Forecast Nucleo Framework from the source code\&.
