.TH "envMotor" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
envMotor
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr PinName \fBMOTOR_ENABLE_PIN\fP = PC_11"
.br
.ti -1c
.RI "constexpr PinName \fBMOTOR_CURRENT_FEEDBACK_PIN\fP = PA_1"
.br
.ti -1c
.RI "constexpr PinName \fBMOTOR_ANALOG_PIN\fP = PA_5"
.br
.ti -1c
.RI "constexpr float \fBMAX_CURR\fP = 2\&.26f"
.br
.ti -1c
.RI "constexpr float \fBKT\fP = 1\&.5038f"
.br
.ti -1c
.RI "constexpr float \fBJM\fP = 0\&.0104f"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "constexpr float envMotor::JM = 0\&.0104f\fC [constexpr]\fP"

.PP
Definition at line 17 of file escon_motor_env\&.h\&.
.SS "constexpr float envMotor::KT = 1\&.5038f\fC [constexpr]\fP"

.PP
Definition at line 16 of file escon_motor_env\&.h\&.
.SS "constexpr float envMotor::MAX_CURR = 2\&.26f\fC [constexpr]\fP"

.PP
Definition at line 15 of file escon_motor_env\&.h\&.
.SS "constexpr PinName envMotor::MOTOR_ANALOG_PIN = PA_5\fC [constexpr]\fP"

.PP
Definition at line 12 of file escon_motor_env\&.h\&.
.SS "constexpr PinName envMotor::MOTOR_CURRENT_FEEDBACK_PIN = PA_1\fC [constexpr]\fP"

.PP
Definition at line 11 of file escon_motor_env\&.h\&.
.SS "constexpr PinName envMotor::MOTOR_ENABLE_PIN = PC_11\fC [constexpr]\fP"

.PP
Definition at line 10 of file escon_motor_env\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Forecast Nucleo Framework from the source code\&.
