.TH "forecast::motorEncoder" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
forecast::motorEncoder
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr float \fBCPR\fP = 20000\&.0f"
.br
.ti -1c
.RI "constexpr float \fBGEAR_RATIO\fP = 1\&.0f"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "constexpr float forecast::motorEncoder::CPR = 20000\&.0f\fC [constexpr]\fP"

.PP
Definition at line 7 of file AB_encoder_motor\&.h\&.
.SS "constexpr float forecast::motorEncoder::GEAR_RATIO = 1\&.0f\fC [constexpr]\fP"

.PP
Definition at line 8 of file AB_encoder_motor\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Forecast Nucleo Framework from the source code\&.
