.TH "include/forecast/Hardware.hpp" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/forecast/Hardware.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <mbed\&.h>\fP
.br
\fC#include <hw/DigitalEncoder/DigitalEncoderAB\&.h>\fP
.br
\fC#include <hw/Motor/EsconMotor\&.h>\fP
.br
\fC#include <utility/math\&.hpp>\fP
.br
\fC#include 'Status\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBforecast::Hardware\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBforecast\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Forecast Nucleo Framework from the source code\&.
