.TH "src/controllers/ImpedanceControl.cpp" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/controllers/ImpedanceControl.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'forecast/controllers/ImpedanceControl\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Forecast Nucleo Framework from the source code\&.
