.TH "motorControl" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
motorControl
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr PinName \fBMOTOR_ENABLE_PIN\fP = PC_10"
.br
.ti -1c
.RI "constexpr PinName \fBMOTOR_CURRENT_FEEDBACK_PIN\fP = PA_0"
.br
.ti -1c
.RI "constexpr PinName \fBMOTOR_ANALOG_PIN\fP = PA_4"
.br
.ti -1c
.RI "constexpr float \fBMAX_CURR\fP = 2\&.26f"
.br
.ti -1c
.RI "constexpr float \fBKT\fP = 1\&.5038f"
.br
.ti -1c
.RI "constexpr float \fBJM\fP = 0\&.0104f"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "constexpr float motorControl::JM = 0\&.0104f\fC [constexpr]\fP"

.PP
Definition at line 17 of file escon_motor\&.h\&.
.SS "constexpr float motorControl::KT = 1\&.5038f\fC [constexpr]\fP"

.PP
Definition at line 16 of file escon_motor\&.h\&.
.SS "constexpr float motorControl::MAX_CURR = 2\&.26f\fC [constexpr]\fP"

.PP
Definition at line 15 of file escon_motor\&.h\&.
.SS "constexpr PinName motorControl::MOTOR_ANALOG_PIN = PA_4\fC [constexpr]\fP"

.PP
Definition at line 12 of file escon_motor\&.h\&.
.SS "constexpr PinName motorControl::MOTOR_CURRENT_FEEDBACK_PIN = PA_0\fC [constexpr]\fP"

.PP
Definition at line 11 of file escon_motor\&.h\&.
.SS "constexpr PinName motorControl::MOTOR_ENABLE_PIN = PC_10\fC [constexpr]\fP"

.PP
Definition at line 10 of file escon_motor\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Forecast Nucleo Framework from the source code\&.
