.TH "include/forecast/Status.hpp" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/forecast/Status.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBforecast\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBforecast::Status\fP : uint8_t { \fBforecast::Status::NO_ERROR\fP = 0, \fBforecast::Status::TICKER_INIT_ERR\fP, \fBforecast::Status::MOTOR_ENCODER_INIT_ERR\fP, \fBforecast::Status::ENV_ENCODER_INIT_ERR\fP, \fBforecast::Status::CONTROL_MOTOR_INIT_ERR\fP, \fBforecast::Status::ENV_MOTOR_INIT_ERR\fP, \fBforecast::Status::TORQUE_SENSOR_INIT_ERR\fP, \fBforecast::Status::FREQ_NOT_KEPT\fP, \fBforecast::Status::COMMUNICATION_ERROR\fP }"
.br
.RI "Contains all the possible errors returned by the methods of this library\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Forecast Nucleo Framework from the source code\&.
