.TH "ticker" 3 "Wed May 6 2020" "Version 0.1.0" "Forecast Nucleo Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ticker
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile bool \fBflag\fP"
.br
.ti -1c
.RI "volatile uint32_t \fBdt_us\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBmTimUserHandle\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "volatile uint32_t ticker::dt_us"

.PP
Definition at line 14 of file App\&.cpp\&.
.SS "volatile bool ticker::flag"

.PP
Definition at line 13 of file App\&.cpp\&.
.SS "TIM_HandleTypeDef ticker::mTimUserHandle"

.PP
Definition at line 16 of file App\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Forecast Nucleo Framework from the source code\&.
